const dummyData  = [
  {
    id:1,
    image:"/images/logo.png",
    title:"UX UI Designer",
    name:"Great Vibes - Information Technology",
    address:"Chennai, Tamilnadu, India (In-office)",
    time:"Part-Time (9.00 am - 5.00 pm IST)",
    experience:"Experience (1 - 2 years)",
    salary:"INR (₹) 30,000 - 60,000 / Month",
    employees:"51-200 employees",
    buttonName:"Apply Now",
    buttonClassName:"primary-button",
  },
  {
    id:2,
    image:"/images/logo.png",
    title:"Developer",
    name:"Great Vibes - Information Technology",
    address:"Chennai, Tamilnadu, India (In-office)",
    time:"Part-Time (9.00 am - 5.00 pm IST)",
    experience:"Experience (1 - 2 years)",
    salary:"INR (₹) 30,000 - 60,000 / Month",
    employees:"51-200 employees",
    buttonName:"External Apply",
    buttonClassName:"secondary-button",
  },
  {
    id:3,
    image:"/images/logo.png",
    title:"Interaction Designer",
    name:"Great Vibes - Information Technology",
    address:"Chennai, Tamilnadu, India (In-office)",
    time:"Part-Time (9.00 am - 5.00 pm IST)",
    experience:"Experience (1 - 2 years)",
    salary:"INR (₹) 30,000 - 60,000 / Month",
    employees:"51-200 employees",
    buttonName:"External Apply",
    buttonClassName:"secondary-button",
  },
  {
    id:4,
    image:"/images/logo.png",
    title:"SEO Analyst",
    name:"Great Vibes - Information Technology",
    address:"Chennai, Tamilnadu, India (In-office)",
    time:"Part-Time (9.00 am - 5.00 pm IST)",
    experience:"Experience (1 - 2 years)",
    salary:"INR (₹) 30,000 - 60,000 / Month",
    employees:"51-200 employees",
    buttonName:"Apply Now",
    buttonClassName:"primary-button",
  },
]

export default dummyData;